Repository Talend/tbd-studio-se, pull requests merged in 2018-06, with the labels that each got.

#791 fix(TDI-40526): Update json-lib dependency
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml
Labels: need review

#774 feat(TBD-6743) initial commit for Qubole distribution
  main/features/org.talend.hadoop.distribution.feature/feature.xml
  main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tELTHiveOutput/tELTHiveOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tPigAggregate/tPigAggregate_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigCoGroup/tPigCoGroup_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigCode/tPigCode_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigCross/tPigCross_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tPigCross/tPigCross_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigCross/tPigCross_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tPigDistinct/tPigDistinct_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigFilterColumns/tPigFilterColumns_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigFilterRow/tPigFilterRow_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigJoin/tPigJoin_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tPigJoin/tPigJoin_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigJoin/tPigJoin_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tPigLoad/tPigLoad_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tPigMap/tPigMap_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigReplicate/tPigReplicate_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigSort/tPigSort_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tPigStoreResult/tPigStoreResult_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tPigStoreResult/tPigStoreResult_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/templates/Pig/RegisterPigLatin.javajet
  main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
  main/plugins/org.talend.hadoop.distribution.qubole/.classpath
  main/plugins/org.talend.hadoop.distribution.qubole/.project
  main/plugins/org.talend.hadoop.distribution.qubole/META-INF/MANIFEST.MF
  main/plugins/org.talend.hadoop.distribution.qubole/OSGI-INF/qubole.xml
  main/plugins/org.talend.hadoop.distribution.qubole/build.properties
  main/plugins/org.talend.hadoop.distribution.qubole/plugin.xml
  main/plugins/org.talend.hadoop.distribution.qubole/pom.xml
  main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/QuboleConstant.java
  main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/QuboleDistribution.java
  main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/modulegroup/QuboleHiveModuleGroup.java
  main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/modulegroup/QubolePigModuleGroup.java
  main/plugins/org.talend.hadoop.distribution.qubole/src/main/java/org/talend/hadoop/distribution/qubole/modulegroup/QubolePigOutputModuleGroup.java
  main/plugins/org.talend.hadoop.distribution/META-INF/MANIFEST.MF
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/qubole/IQuboleDistribution.java
  pom.xml
Labels: Build running

#793 feat(TBD-6295) initial commit for Databricks distribution
  main/features/org.talend.hadoop.distribution.feature/feature.xml
  main/plugins/org.talend.hadoop.distribution.databricks/.classpath
  main/plugins/org.talend.hadoop.distribution.databricks/.project
  main/plugins/org.talend.hadoop.distribution.databricks/META-INF/MANIFEST.MF
  main/plugins/org.talend.hadoop.distribution.databricks/OSGI-INF/databricks.xml
  main/plugins/org.talend.hadoop.distribution.databricks/build.properties
  main/plugins/org.talend.hadoop.distribution.databricks/plugin.xml
  main/plugins/org.talend.hadoop.distribution.databricks/pom.xml
  main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksConstant.java
  main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/DatabricksDistribution.java
  main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/modulegroup/DatabricksHiveOnSparkModuleGroup.java
  main/plugins/org.talend.hadoop.distribution.databricks/src/main/java/org/talend/hadoop/distribution/databricks/modulegroup/DatabricksSparkBatchModuleGroup.java
  main/plugins/org.talend.hadoop.distribution/META-INF/MANIFEST.MF
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/HadoopComponent.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/constants/databricks/IDatabricksDistribution.java
  pom.xml
  test/features/org.talend.bigdata.se.test.feature/feature.xml
  test/plugins/org.talend.hadoop.distribution.databricks.test/.classpath
  test/plugins/org.talend.hadoop.distribution.databricks.test/.project
  test/plugins/org.talend.hadoop.distribution.databricks.test/META-INF/MANIFEST.MF
  test/plugins/org.talend.hadoop.distribution.databricks.test/META-INF/eclipse.inf
  test/plugins/org.talend.hadoop.distribution.databricks.test/build.properties
  test/plugins/org.talend.hadoop.distribution.databricks.test/pom.xml
  test/plugins/org.talend.hadoop.distribution.databricks.test/src/org/talend/hadoop/distribution/databricks/test/DatabricksClassLoaderTest.java
  test/plugins/org.talend.hadoop.distribution.databricks.test/src/org/talend/hadoop/distribution/databricks/test/DatabricksDistributionTest.java
  test/plugins/org.talend.hadoop.distribution.databricks.test/src/org/talend/hadoop/distribution/databricks/test/modulegroup/DatabricksHiveOnSparkModuleGroupTest.java
  test/plugins/org.talend.hadoop.distribution.databricks.test/src/org/talend/hadoop/distribution/databricks/test/modulegroup/DatabricksSparkBatchModuleGroupTest.java
Labels: work in progress
