Repository Talend/tbd-studio-se, pull requests merged in 2020-09, with the labels that each got.

#1598 fix(TDI-30522): revert all fixes
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet
Labels: need review

#1607 feat(TBD-11232): normalize builds
  continuous-integration/Jenkinsfile
  continuous-integration/commit-check.py
  continuous-integration/requirement.txt
  continuous-integration/sanity-check.py
  continuous-integration/version-check.py
Labels: donotmerge

#1332 fix(TBD-10291): fix parquet prefix package for HDP3 and CDH6
  main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_main.javajet
  main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.hdpx/src/org/talend/hadoop/distribution/hdpx/HDP3xxDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/EParquetPackagePrefix.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/MRComponent.java
Labels: donotmerge

#1637 fix(TBD-11316): fix MapR610 to use hbase 2x
  main/plugins/org.talend.hadoop.distribution.mapr610/src/org/talend/hadoop/distribution/mapr610/MapR610Distribution.java
Labels: Build running
