Repository Talend/tbd-studio-se, pull requests merged in 2020-06, with the labels that each got.

#1435 fix(TDI-30505): Backport from "master" to "maintenance/7.3" branch
  main/plugins/org.talend.designer.components.bigdata/components/tMemSQLOutput/tMemSQLOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
Labels: backport, need review

#1461 fix(TDI-44253): tMongoDBOutput dates processing (#1419)
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet
Labels: backport, need review

#1462 fix(TDI-44253): tMongoDBOutput dates processing (#1419)
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet
Labels: need review

#1463 fix(TDI-44253): tMongoDBOutput dates processing (#1419)
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet
Labels: backport, need review

#1465 fix(TBD-10838): 'URLClassLoader cannot be resolved to a type' in tHDFSConnection after Studio patch
  main/plugins/org.talend.designer.components.bigdata/components/tHBaseConnection/tHBaseConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSConnection/tHDFSConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaConnection/tImpalaConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_begin.javajet
Labels: Build running

#1468 feat(TDI-44039): update version of dataproc (#1467)
  main/plugins/org.talend.hadoop.distribution.dataproc14/plugin.xml
Labels: backport

#1403 fix(TDI-44234): Ensure parallel threads terminates before Main thread stops.
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet
Labels: need review

#1460 fix(TDI-44234): Ensure parallel threads terminates before Main thread stops.
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet
Labels: backport, need review
