Repository Talend/tbd-studio-se, pull requests merged in 2020-08, with the labels that each got.

#1501 fix(TDI-44486): Updated httpcore and httpclient for all components.
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml
Labels: need review

#1539 fix(TDI-44486): backport to master branch.
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml
Labels: backport, need review

#1550 feat(TBD-10362): Add pool ID to databricks (#1436)
  main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
  main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
Labels: Build running

#1525 feat(TBD-10671): added support for generic arguments
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_commandline.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_javaapi.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_commandline.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_javaapi.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_commandline.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_javaapi.javajet
Labels: donotmerge

#1585 fix(TDI-30522): backport to "master"
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet
Labels: backport, need review

#1571 fix(TDI-30522): reworked fix.
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet
Labels: need review
