Repository Talend/tbd-studio-se, pull requests merged in 2020-05, with the labels that each got.

#1377 fix(TBD-10206): Upgrade httpclient to align with other components
  main/plugins/org.talend.designer.components.bigdata/components/tELTHiveMap/tELTHiveMap_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHBaseConnection/tHBaseConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHBaseInput/tHBaseInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHBaseOutput/tHBaseOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHCatalogOutput/tHCatalogOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSCompare/tHDFSCompare_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSConnection/tHDFSConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSCopy/tHDFSCopy_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSDelete/tHDFSDelete_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSExist/tHDFSExist_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSGet/tHDFSGet_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSInput/tHDFSInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSList/tHDFSList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSOutput/tHDFSOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSOutputRaw/tHDFSOutputRaw_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSProperties/tHDFSProperties_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSPut/tHDFSPut_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSRename/tHDFSRename_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSRowCount/tHDFSRowCount_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveCreateTable/tHiveCreateTable_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveInput/tHiveInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHiveLoad/tHiveLoad_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaCreateTable/tImpalaCreateTable_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaInput/tImpalaInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaLoad/tImpalaLoad_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaOutput/tImpalaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tImpalaRow/tImpalaRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMapRDBConnection/tMapRDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMapRDBInput/tMapRDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMapRDBOutput/tMapRDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopExport/tSqoopExport_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/sqoop-1.4.2-mapr.jar
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImport/tSqoopImport_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopImportAllTables/tSqoopImportAllTables_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tSqoopMerge/tSqoopMerge_java.xml
Labels: Build running

#1396 fix(TBD-10340): [Spark Streaming, CDH 6.1] NoClassDefFoundError on tH…-R2020-05_TBD
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
Labels: Build running

#1401 fix(TDI-44221): Updated output message parsing template due to driver…
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet
Labels: need review

#1414 fix(TDI-44221): Updated output message parsing template due to driver update.
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet
Labels: backport, need review

#1374 fix(TDI-30505): Fix for MemSQL and SAPHana output components
  main/plugins/org.talend.designer.components.bigdata/components/tMemSQLOutput/tMemSQLOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
Labels: need review

#1419 fix(TDI-44253): tMongoDBOutput dates processing
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_3_5_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_main_below_3_5.javajet
Labels: need review

#1428 fix(TBD-10606): remove hive-exec-1.2.1 dependency for cdh6.1 disto
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
Labels: Build running
