Repository Talend/tbd-studio-se, pull requests merged in 2020-10, with the labels that each got.

#1674 feat(TBD-10087): CP Assume Role feature to R10
  main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
  main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
  main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/EMR5150Distribution.java
  main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
  main/plugins/org.talend.hadoop.distribution.emr5290/src/main/java/org/talend/hadoop/distribution/emr5290/EMR5290Distribution.java
  main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
  main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/hdp/DynamicHDPSparkBatchModuleGroup.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/hdp/DynamicHDPSparkStreamingModuleGroup.java
Labels: Build running

#1678 fix(TBD-11355): custom class path is used in lightweightmode (#1636)
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/component/SparkComponent.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/AbstractDynamicDistributionTemplate.java
Labels: Build running

#1675 feat(TBD-10087): AWS S3 - extend STS AssumeRole field support CP to master
  main/plugins/org.talend.hadoop.distribution.cdh5100/plugin.xml
  main/plugins/org.talend.hadoop.distribution.cdh5120/plugin.xml
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH5_13_0.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh5xTemplate.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh5x/CDH5xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.cdh5x/src/org/talend/hadoop/distribution/cdh6x/CDH6xDistributionTemplate.java
  main/plugins/org.talend.hadoop.distribution.emr5150/plugin.xml
  main/plugins/org.talend.hadoop.distribution.emr5150/src/main/java/org/talend/hadoop/distribution/emr5150/EMR5150Distribution.java
  main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
  main/plugins/org.talend.hadoop.distribution.emr5290/src/main/java/org/talend/hadoop/distribution/emr5290/EMR5290Distribution.java
  main/plugins/org.talend.hadoop.distribution.hdp250/plugin.xml
  main/plugins/org.talend.hadoop.distribution.hdp260/plugin.xml
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_3_1_4_12_1.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp3xxTemplate.json
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/AbstractDistribution.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/hdp/DynamicHDPSparkBatchModuleGroup.java
  main/plugins/org.talend.hadoop.distribution/src/main/java/org/talend/hadoop/distribution/dynamic/template/modulegroup/hdp/DynamicHDPSparkStreamingModuleGroup.java
Labels: Build running

#1692 chore(TDI-44770): upgrade snakeyaml version, remove jar
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/snakeyaml-1.6.jar
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
Labels: need review

#1688 fix(TBD-11491): missing dependency for kinesis streaming
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/builtin/cdhx/Cloudera_CDH6_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdh5x/resources/template/cdhx/cdh6xTemplate.json
Labels: donotmerge
