Repository Talend/tbd-studio-se, pull requests merged in 2020-12, with the labels that each got.

#1763 chore(TDI-44770): upgrade snakeyaml version, remove jar (#1692)
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/snakeyaml-1.6.jar
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
Labels: Build running

#1626 fix(TDI-30522):Address Useless commit log issue
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tSAPHanaOutput/tSAPHanaOutput_main.javajet
Labels: need review

#1778 fix(TDI-45260): update talend file enhanced library
  main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSInput/tHDFSInput_java.xml
Labels: donotmerge, need review

#1777 fix(TDI-45260): update talend file enhanced library
  main/plugins/org.talend.designer.components.bigdata/components/tHCatalogInput/tHCatalogInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tHDFSInput/tHDFSInput_java.xml
Labels: donotmerge

#1774 fix(TBD-11772):S3 component doesn't work on CDP 7.1.1
  main/plugins/org.talend.hadoop.distribution.cdp/resources/builtin/cdp/Cloudera_CDP_7_1_1.json
  main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
  main/plugins/org.talend.hadoop.distribution.cdp/src/main/java/org/talend/hadoop/distribution/cdp/CDP7xDistributionTemplate.java
Labels: donotmerge, wip
