Repository Talend/tbd-studio-se, pull requests merged in 2020-02, with the labels that each got.

#1260 fix(TBD-9842): Databricks jobs not running on several regions
  main/plugins/org.talend.hadoop.distribution.dbr350/plugin.xml
  main/plugins/org.talend.hadoop.distribution.dbr550/plugin.xml
Labels: to be merged

#1258 fix(TDI-43631): Update json-lib dependency
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBWriteConf/tMongoDBWriteConf_java.xml
Labels: need review

#1281 chore[TBD-9558]: remove classloader junit of HDInsight3.4
  test/plugins/org.talend.hadoop.distribution.hdinsight340.test/src/org/talend/hadoop/distribution/hdinsight340/test/HDInsight34ClassLoaderTest.java
Labels: Build running
