Repository Talend/tbd-studio-se, pull requests merged in 2020-03, with the labels that each got.

#1311 fix(TDI-43740): Edited MONGODB_DIR.NAME property to All-lowercase
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBBulkLoad/tCosmosDBBulkLoad_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_messages.properties
Labels: need review

#1313 fix(TBD-9956):Sqoop issue with Java API/parquet format/HDP 2.6
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/builtin/hdpx/Hortonworks_HDP_2_6_0_3_8.json
  main/plugins/org.talend.hadoop.distribution.hdpx/resources/template/hdpx/hdp2xxTemplate.json
Labels: needs review

#1295 feat(TDI-43770):upgrade httpclient,httpcore,logging,codec
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBConnection/tCouchDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBInput/tCouchDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBOutput/tCouchDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBReadConf/tCouchDBReadConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCouchDBWriteConf/tCouchDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakBucketList/tRiakBucketList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakConnection/tRiakConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakInput/tRiakInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakKeyList/tRiakKeyList_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tRiakOutput/tRiakOutput_java.xml
Labels: need review

#1312 fix(TDI-43810): Add ignore service attr checkbox for mongo and cosmos…
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
Labels: need review

#1328 fix(TDI-43810): Add ignore service attr checkbox for mongo and cosmos…
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
Labels: backport, need review

#1329 fix(TDI-43810): Add ignore service attr checkbox for mongo and cosmos…
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
Labels: backport, need review

#1330 fix(TDI-43810): Add ignore service attr checkbox for mongo and cosmos…
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
Labels: backport, need review

#1298 feat(TDI-43754): upgrade AWS SDK.
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBInput/tDynamoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tDynamoDBOutput/tDynamoDBOutput_java.xml
Labels: need review

#1344 TPS-3909:[7.3.1] DI job with Big Data components fail when using the custom hadoop conf file location feature(TUP-26580)
  main/plugins/org.talend.repository.nosql/src/messages.properties
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/mongodb/IMongoDBAttributes.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/provider/mongodb/MongoDBDNDProvider.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/mongodb/MongoDBConnectionUtil.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/service/NOSQLService.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/ui/common/AbstractNoSQLConnForm.java
Labels: Build running
