Repository Talend/tbd-studio-se, pull requests merged in 2021-03, with the labels that each got.

#1894 chore(TUP-29397): CVE on jackson-core-2.4.6.jar
  main/plugins/org.talend.repository.hadoopcluster.configurator/pom.xml
Labels: Build running

#1895 fix(TDI-45725): avoid IndexOutOfBoundsException for tCosmosDBBulkLoad component.
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBBulkLoad/tCosmosDBBulkLoad_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBBulkLoad/tMongoDBBulkLoad_main.javajet
Labels: backport, need review

#1880 feat(TDI-45590): tCosmosDB drivers and API update
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBClose/tCosmosDBClose_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_messages.properties
Labels: need review

#1883 feat(TDI-44106): add possibility to select fields to be returned.
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
Labels: need review

#1905 feat(TDI-45590): BP_Release_patch_731: tCosmosDB drivers and API update (#1880)
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBClose/tCosmosDBClose_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_messages.properties
Labels: backport, need review

#1906 feat(TDI-44106): add possibility to select fields to be returned. (#1883)
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
Labels: backport, need review

#1907 fix(TBD-11943): fix snowflake and spark version for dbr73 (#1901)
  main/plugins/org.talend.hadoop.distribution.dbr73x/plugin.xml
  main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xConstant.java
  main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/DBR73xDistribution.java
  main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/modulegroup/DBR73xSparkBatchModuleGroup.java
  main/plugins/org.talend.hadoop.distribution.dbr73x/src/main/java/org/talend/hadoop/distribution/dbr73x/modulegroup/node/DBR73xSnowflakeNodeModuleGroup.java
Labels: Build running

#1922 feat(TDI-45590): BP_741_ tCosmosDB drivers and API update (#1880)
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBClose/tCosmosDBClose_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBConnection/tCosmosDBConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBOutput/tCosmosDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBRow/tCosmosDBRow_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_begin_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_main_below_4_4_X.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBWriteConf/tCosmosDBWriteConf_messages.properties
Labels: backport, need review

#1923 feat(TDI-44106): BP_741: add possibility to select fields to be returned. (#1883)
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCosmosDBInput/tCosmosDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
Labels: backport, need review
