Repository Talend/tbd-studio-se, pull requests merged in 2021-05, with the labels that each got.

#1982 fix(TUP-30377):TUP-30377 Move the "Allow specific characters (UTF8,...)" preference setting to project setting.
  main/plugins/org.talend.repository.hcatalog/src/org/talend/repository/hcatalog/ui/HCatalogSchemaForm.java
Labels: Build running

#1958 fix(TDI-45824): Update jersey for Neo4j
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
Labels: need review

#1992 fix(TDI-45824): Update for neo4j 2.1 also
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
Labels: Build running, need review

#1998 Dsylaiev/tdi 46060 revert for neo4j 21x and 1xx
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
Labels: revert

#1985 fix(TDI-45986): remove handling of unsupported exceptions.
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_end_0.9.0.x.javajet
Labels: needs review
