Repository Talend/tbd-studio-se, pull requests merged in 2021-12, with the labels that each got.

#2346 fix(TDI-44321): Regain message change
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBConnection/tMongoDBConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSDelete/tMongoDBGridFSDelete_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSGet/tMongoDBGridFSGet_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSList/tMongoDBGridFSList_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSProperties/tMongoDBGridFSProperties_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBGridFSPut/tMongoDBGridFSPut_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBInput/tMongoDBInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBOutput/tMongoDBOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tMongoDBRow/tMongoDBRow_messages.properties
Labels: need review, Build running, backport

#2351 fix(TBD-13262):HWC/Knox job is not able to connect to cluster
  main/plugins/org.talend.hadoop.distribution.cdp/resources/template/cdp/cdp7xTemplate.json
Labels: Build running

#2363 feat(TDI-46470): tKafkaOutput NB_LINES and other statistical after variables
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties
Labels: need review

#2364 feat(TDI-46470): tKafkaOutput NB_LINES and other statistical after variables
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties
Labels: need review, backport

#2330 feat(TUP-33610): align db version to di components.
  main/plugins/org.talend.repository.nosql/plugin.xml
  main/plugins/org.talend.repository.nosql/src/messages.properties
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/cassandra/ICassandraConstants.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/common/neo4j/INeo4jConstants.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/cassandra/CassandraConnForm.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/mongodb/MongoDBConnForm.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/ui/neo4j/Neo4jConnForm.java
  main/plugins/org.talend.repository.nosql/src/org/talend/repository/nosql/db/util/neo4j/Neo4jConnectionUtil.java
Labels: Build running

#2381 fix(TBD-12809):Compile error on Spark job with Hive components using …
  main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
Labels: Build running

#2342 feat(TDI-46430): Kafka Input Output Avro support
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tSetKeystore_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/2.4.x/tKafkaCreateTopic_begin_2.4.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_main_0.10.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
  main/plugins/org.talend.designer.components.bigdata/plugin.xml
Labels: need review

#2387 feat(TDI-46430): Kafka Input Output Avro support (#2342)
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tSetKeystore_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/2.4.x/tKafkaCreateTopic_begin_2.4.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_begin_0.10.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.10.0.x/tKafkaInput_main_0.10.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/0.9.0.x/tKafkaInput_begin_0.9.0.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_finally.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
  main/plugins/org.talend.designer.components.bigdata/plugin.xml
Labels: need review, Build running, backport

#2384 fix(TBD-13310):CVE: jackson-mapper(core)-asl-1.9.15-TALEND
  main/plugins/org.talend.hadoop.distribution.emr5290/plugin.xml
  main/plugins/org.talend.hadoop.distribution.hdinsight400/plugin.xml
Labels: Build running

#2395 fix(TDI-47212): CVE: jackson-mapper(core)-asl-1.9.15-TALEND
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutput/tNeo4jOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jOutputRelationship/tNeo4jOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
  main/plugins/org.talend.repository.nosql/plugin.xml
Labels: Build running
