Repository Talend/tbd-studio-se, pull requests merged in 2022-10, with the labels that each got.

#2885 fix(TDI-48318): fix CVE for Netty.
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutput/tNeo4jBatchOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutputRelationship/tNeo4jBatchOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchSchema/tNeo4jBatchSchema_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
Labels: need review

#2913 fix(TDI-48318): BP_801: fix CVE for Netty.
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraBulkExec/tCassandraBulkExec_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraConnection/tCassandraConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraInput/tCassandraInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutput/tCassandraOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraOutputBulk/tCassandraOutputBulk_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tCassandraRow/tCassandraRow_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutput/tNeo4jBatchOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutputRelationship/tNeo4jBatchOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchSchema/tNeo4jBatchSchema_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
Labels: need review, backport

#2921 feat(TDI-47598): Kafka support version 3.2 (#2904)
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCommit/tKafkaCommit_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaConnection/tKafkaConnection_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/2.4.x/tKafkaCreateTopic_begin_2.4.x.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaCreateTopic/tKafkaCreateTopic_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_begin.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_end.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaInput/tKafkaInput_util.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_main.javajet
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_messages.properties
  main/plugins/org.talend.designer.components.bigdata/components/tKafkaOutput/tKafkaOutput_util.javajet
Labels: backport

#2936 feat(TDI-48392): Mark neo4j v3 as deprecated
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutput/tNeo4jBatchOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutputRelationship/tNeo4jBatchOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchSchema/tNeo4jBatchSchema_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jClose/tNeo4jClose_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
Labels: need review

#2950 feat(TDI-48392): Mark neo4j v3 as deprecated (#2936)
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutput/tNeo4jBatchOutput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchOutputRelationship/tNeo4jBatchOutputRelationship_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jBatchSchema/tNeo4jBatchSchema_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jClose/tNeo4jClose_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jConnection/tNeo4jConnection_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jImportTool/tNeo4jImportTool_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jInput/tNeo4jInput_java.xml
  main/plugins/org.talend.designer.components.bigdata/components/tNeo4jRow/tNeo4jRow_java.xml
Labels: backport
